### ISSUE TITLE
regular.txt and iron.txt

### ISSUE THREAD

**Issue by vinayakumarr** [dylandrover/keras_tutorial#1]
could you please tell what these values? how did you convert text to numeric values. could you please add me readme file

**Comment by manashmandal** [comment]
I need to know too, @dylandrover , please answer!

**Comment by dylandrover** [comment]
Apologies for the late response, it's been a hectic month.

**Comment by dylandrover** [comment]
Hey, sorry for the late response on this issue. 
I've added a more thorough README file that I hope explains how I attained the vectors used for training.   I also added the scripts that I used to generate them in the first place. If you have further questions about this process please just comment here again and I'll respond as soon as I can.

**Comment by manashmandal** [comment]
Thanks a lot, really appreciated it! Will let you know if I have any further questions.
